name: build_citizen_watch_android

on:
  push:
    tags : 
      - v*

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.16.0-0.3.pre'
          channel: 'any'
      - name: Install Dependencies
        run: flutter packages get
      
      
      # - name: Run tests
      #   run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2.3
        with:
          fileName: 'keystore/release_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
            
      - name: "Build APKs"
        id: build-apks
        run: | 
          flutter build apk -t lib/main.dart --split-per-abi
          echo "built-apks=build/app/outputs/flutter-apk/*.apk" >> $GITHUB_OUTPUT

        env: 
          ANDROID_KEYSTORE_PATH: ${{ steps.decode_keystore.outputs.filePath }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        
      - name: "List APKs"
        run: |
          ls -R build/app/outputs/flutter-apk/        


      - name: Create Github Releases
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: build/app/outputs/flutter-apk/*.apk

      # - name: upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_APP_ID}}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     releaseNotes: ${{ github.event.release.body }}
      #     groups: internal
      #     file: build/app/outputs/bundle/productionRelease/app-production-release.aab